# Generated by Django 3.2.5 on 2022-07-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_teachers',
            name='approval_manager',
            field=models.CharField(max_length=50),
        ),
    ]
