# Generated by Django 3.2.5 on 2022-07-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0002_alter_approved_teachers_approval_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='approved_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name1', models.CharField(max_length=50)),
                ('stud_name2', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('class_alloted', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('teacher_alloted', models.CharField(max_length=50)),
                ('approval_teacher', models.CharField(max_length=50)),
                ('approval_date', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=50)),
            ],
        ),
    ]
