# Generated by Django 3.2.5 on 2022-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0004_auto_20220724_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='XI_A_attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=50)),
                ('reg_no', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('Attendence', models.CharField(max_length=50)),
                ('attendence_taken', models.CharField(max_length=50)),
            ],
        ),
    ]
