# Generated by Django 3.2.5 on 2022-08-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0006_rename_date_xi_a_attendence_date_of_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='xi_a_attendence',
            name='attendence_status',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
