# Generated by Django 3.2.5 on 2022-08-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0007_xi_a_attendence_attendence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='xi_a_attendence',
            name='attendance_stat',
            field=models.CharField(default='Attendance Already Taken!', max_length=100),
            preserve_default=False,
        ),
    ]
