# Generated by Django 3.2.5 on 2022-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0014_xl_a_marksheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='xl_a_marksheets',
            name='maths_mark_1',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xl_a_marksheets',
            name='maths_mark_2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xl_a_marksheets',
            name='maths_mark_3',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xl_a_marksheets',
            name='maths_mark_4',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xl_a_marksheets',
            name='maths_mark_5',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xl_a_marksheets',
            name='maths_mark_6',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
