# Generated by Django 3.2.5 on 2022-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0018_l_a_marksheets_l_b_marksheets_ll_a_marksheets_ll_b_marksheets_ll_c_marksheets_lll_a_marksheets_lll_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('teacher_incharge', models.CharField(max_length=50)),
                ('exam_name_1', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('malayalam', models.CharField(max_length=50)),
                ('maths', models.CharField(max_length=50)),
                ('computer', models.CharField(max_length=50)),
                ('science', models.CharField(max_length=50)),
                ('social', models.CharField(max_length=50)),
                ('hindi', models.CharField(max_length=50)),
                ('gk', models.CharField(max_length=50)),
                ('physics', models.CharField(max_length=50)),
                ('chemistry', models.CharField(max_length=50)),
                ('biology', models.CharField(max_length=50)),
                ('phy_edcu', models.CharField(max_length=50)),
                ('music', models.CharField(max_length=50)),
                ('art', models.CharField(max_length=50)),
            ],
        ),
    ]
