# Generated by Django 3.2.5 on 2022-09-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0020_remove_class_subject_exam_name_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_teacher', models.CharField(max_length=50)),
                ('announcement', models.CharField(max_length=200)),
                ('anno_status', models.CharField(max_length=50)),
            ],
        ),
    ]
