# Generated by Django 3.2.5 on 2022-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0021_class_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=10)),
                ('chapter', models.CharField(max_length=10)),
                ('cls_require', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('extra_cls', models.CharField(max_length=100)),
                ('portion_status', models.CharField(max_length=50)),
            ],
        ),
    ]
