# Generated by Django 3.2.5 on 2022-09-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0023_auto_20220916_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_portion',
            new_name='add_portions',
        ),
    ]
