# Generated by Django 3.2.5 on 2022-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0024_rename_add_portion_add_portions'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculaty_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('message_from', models.CharField(max_length=250)),
                ('message_to', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
                ('message_date', models.DateTimeField()),
                ('message_status', models.CharField(max_length=50)),
            ],
        ),
    ]
