# Generated by Django 3.2.5 on 2022-09-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgcs_admin', '0025_faculaty_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculaty_messages',
            name='meage_reply',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
